improve workflow when pgpass not found

diff --git a/.github/workflows/splunkconf-backup-test.yml b/.github/workflows/splunkconf-backup-test.yml
--- a/.github/workflows/splunkconf-backup-test.yml
+++ b/.github/workflows/splunkconf-backup-test.yml
@@ -312,8 +312,9 @@ jobs:
               PGPASS_FILE="${SPLUNK_HOME}/var/packages/data/postgres/db/.pgpass"
               echo "Found .pgpass at ${PGPASS_FILE}"
             else
+              echo ".pgpass not found at usual location, trying to find it anyway (if success please fix workflow for new location)"
               docker exec --user ${SPLUNK_USER} splunk bash -c \
-              "find /opt/splunk -name .pgpass 2>/dev/null || echo '❌ Error : No .pgpass found via find command '" || true
+              "find ${SPLUNK_HOME} -name .pgpass -print 2>/dev/null || echo '❌ Error : No .pgpass found via find command '" || true
               exit 1
             fi
 
