add delay for pg test

diff --git a/.github/workflows/splunkconf-backup-test.yml b/.github/workflows/splunkconf-backup-test.yml
--- a/.github/workflows/splunkconf-backup-test.yml
+++ b/.github/workflows/splunkconf-backup-test.yml
@@ -286,7 +286,24 @@ jobs:
             # for splunk 10.2 and newer, process name is  splunk-postgres
             docker exec --user ${SPLUNK_USER} splunk bash -c \
             "ps aux 2>/dev/null | grep -i [p]ostgres |  grep -v grep || echo '❌ Error : No Postgres process found'" || true
-
+            echo "Waiting and redoing test"
+            sleep 10
+            "ps aux 2>/dev/null | grep -i [p]ostgres |  grep -v grep || echo '❌ Error : No Postgres process found'" || true
+            echo "Waiting and redoing test"
+            sleep 10
+            "ps aux 2>/dev/null | grep -i [p]ostgres |  grep -v grep || echo '❌ Error : No Postgres process found'" || true
+            echo "Waiting and redoing test"
+            sleep 10
+            "ps aux 2>/dev/null | grep -i [p]ostgres |  grep -v grep || echo '❌ Error : No Postgres process found'" || true
+            echo "Waiting and redoing test"
+            sleep 10
+            "ps aux 2>/dev/null | grep -i [p]ostgres |  grep -v grep || echo '❌ Error : No Postgres process found'" || true
+            echo "Waiting and redoing test"
+            sleep 10
+            "ps aux 2>/dev/null | grep -i [p]ostgres |  grep -v grep || echo '❌ Error : No Postgres process found'" || true
+            echo "Waiting 60s and redoing test"
+            sleep 60
+            "ps aux 2>/dev/null | grep -i [p]ostgres |  grep -v grep || echo '❌ Error : No Postgres process found'" || true
             # Check if .pgpass file exists (indicates Postgres credentials are configured)
             echo ""
             echo "--- Checking for Postgres credentials file ---"
