fix typo - 2

diff --git a/.github/workflows/splunkconf-backup-test.yml b/.github/workflows/splunkconf-backup-test.yml
--- a/.github/workflows/splunkconf-backup-test.yml
+++ b/.github/workflows/splunkconf-backup-test.yml
@@ -275,7 +275,7 @@ jobs:
           if [ "${IS_UF}" = "1" ]; then
             echo "UF : disabling postsgres check"
             exit 0
-          elif [ "$MAJOR_VERSION" -le 10 ]; then
+          elif [ "$MAJOR_VERSION" -le 9 ]; then
             echo "Splunk Enterprise less than 10, no PG"
             exit 0
           else
@@ -285,7 +285,7 @@ jobs:
             # if Splunk 10.0 process is named postgres
             # for splunk 10.2 and newer, process name is  splunk-postgres
             docker exec --user ${SPLUNK_USER} splunk bash -c \
-            "ps aux 2>/dev/null | grep -i [p]ostgres |  grep -v grep | echo '❌ Error : No Postgres process found'" || true
+            "ps aux 2>/dev/null | grep -i [p]ostgres |  grep -v grep || echo '❌ Error : No Postgres process found'" || true
 
             # Check if .pgpass file exists (indicates Postgres credentials are configured)
             echo ""
